import base64
import binascii
import json

from pyrogram import filters, StopPropagation

import bot_legacy
import enhancements
from handlers.database import db

Bot = bot_legacy.Bot


def _decode_token(value):
    value = str(value or "").strip()
    # Current links contain a base64url-encoded token. Accept raw tokens too,
    # so links generated by either format continue to work.
    try:
        padded = value + ("=" * ((4 - len(value) % 4) % 4))
        decoded = base64.urlsafe_b64decode(padded.encode("ascii")).decode("utf-8")
        if decoded:
            return decoded
    except (ValueError, UnicodeError, binascii.Error):
        pass
    return value


@Bot.on_message(filters.private & filters.command("start"), group=-3)
async def fixed_direct_start(bot, m):
    if len(m.command) < 2:
        return

    payload = m.command[1]
    if payload.startswith("HJDirect_"):
        kind = "direct:"
        token = _decode_token(payload[len("HJDirect_"):])
    elif payload.startswith("HJDirectBatch_"):
        kind = "direct_batch:"
        token = _decode_token(payload[len("HJDirectBatch_"):])
    else:
        return

    raw = await db._get_setting(kind + token, "")
    # Backward/forward compatibility: if a malformed or legacy client passed
    # an encoded token, also try the literal value.
    if not raw and token != payload.split("_", 1)[-1]:
        raw = await db._get_setting(kind + payload.split("_", 1)[-1], "")

    if not raw:
        await m.reply_text("❌ Could not open direct link.\nThis direct link is invalid or no longer available.")
        raise StopPropagation

    try:
        data = json.loads(raw)
        if kind == "direct:":
            items = [(int(data["chat_id"]), int(data["message_id"]))]
        else:
            items = [(int(x["chat_id"]), int(x["message_id"])) for x in data]
        if not items:
            raise ValueError("This direct batch contains no messages.")
        await enhancements._deliver_direct(bot, int(m.from_user.id), items)
    except Exception as exc:
        await m.reply_text(f"❌ Could not open direct link.\n`{exc}`")
    raise StopPropagation
